spring:
  kafka: 
      bootstrap-servers: localhost:9093
  application:
    name: Kafka-Consumer
kafka:
  src:
    bootstrap-servers: kafka-0.mh-nfaesozrbxarqnjfnzecnsr.eu-de.containers.appdomain.cloud:9093
    username: token
    password: UwMSwKMKJXOI-SXJQAGJIZ2mOr6KbcL4iidz66FxY_Ox
    topic: mmo275Test
    properties:
      security:
        protocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule required username="IDTUceqx3tUVwW2E" password="OeVEuhLeRkEPE0Uo7GFNH54KdlrQ0Uyo";   
    truststore-location: cacerts
    truststore-password: changeit
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR    
server:
  port:
    8093